# Use the official MongoDB image from Docker Hub
FROM mongo

# Optionally, you can specify a custom configuration for MongoDB
# COPY mongod.conf /etc/mongod.conf

# Expose MongoDB port
EXPOSE 27017

# Start MongoDB when the container starts
CMD ["mongod"]